pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = 'dockerhub'
        IMAGE_NAME = 'iddhawan01/jenkins-test'
    }

    stages {
        stage('Clone Repository') {
            steps {
                echo "Cloning repository..."
                git branch: 'main', url: 'https://github.com/iddhawan01/datalocaltogithub.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                echo "Building Docker image..."
                cd 04-docker-push
                docker build -t my-first-image .
                '''
            }
        }

        stage('Tag Docker Image') {
            steps {
                sh '''
                echo "Tagging image..."
                docker tag my-first-image ${IMAGE_NAME}:latest
                '''
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: DOCKERHUB_CREDENTIALS, usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh '''
                    echo "Logging in to Docker Hub..."
                    echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
                    '''
                }
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                sh '''
                echo "Pushing Docker image..."
                docker push ${IMAGE_NAME}:latest
                '''
            }
        }
    }

    post {
        success {
            echo "Use Case 4: Docker image pushed successfully to Docker Hub!"
        }
        failure {
            echo "Pipeline failed — check error above."
        }
    }
}
